### ISSUE TITLE
log4j.properties is ignored

### ISSUE THREAD

**Issue by anuragopenxcell** [savoirtech/slf4j-json-logger#4]
I used the gradle for slf4j-json-logger in my project but the output is always in console and in the default pattern. It is ignoring my log4j.properties file (src/main/resources). Can you please tell me if I am doing something wrong?

**Comment by mrogghe** [comment]
How are you setting up and using the the logger in your code?  Can you paste in a snippet of the code including the imports please?

**Comment by mrogghe** [comment]
Also, do you have an additional log4j.properties or other log configuration file in src/test/resources ?

**Comment by artnaseef** [comment]
Any update here?  If not, I'll close this issue.
